[project]
name = "rec-sys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "google-cloud-aiplatform>=1.80.0",
    "google-cloud-pipeline-components>=2.18.0",
    "google-cloud-storage>=2.19.0",
    "joblib>=1.4.2",
    "kfp>=2.10.1",
    "nox>=2025.2.9",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "safety>=3.3.0",
    "streamlit>=1.42.0",
    "torch>=2.6.0",
]

[project.scripts]
rec-sys = "rec_sys:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["isort>=6.0.0", "mypy>=1.15.0", "pytest>=8.3.4", "ruff>=0.9.5"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",   #pycodestyle
    "F",   #Pyflakes 
    "UP",  #pyupgrade
    "B",   #flake8-bugbear
    "D",   #pydocstyle
    "SIM", #flake8-simplify (SIM)
    "I",   #isort
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
ignore_missing_imports = true
