name: python-packaging
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lock_checking:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uv lock --locked

    linting:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install ruff
        - run: ruff check

    formatting:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install ruff
        - run: ruff format
    
    types:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install mypy
        - run: mypy .

    tests:
        runs-on: ubuntu-latest
        needs: [linting, formatting, types]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - uses: ./.github/actions/setup
        - run: uv sync
        # - run: uv run pytest
    
    build:
        runs-on: ubuntu-latest
        needs: [tests]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        - uses: ./.github/actions/setup
        - name: "Setup the UV dependencies"  
          run: uv sync
        - name: Build the artifact
          run: uv build --wheel
        - name: Upload built artifacts
          uses: actions/upload-artifact@v4
          with:
            name: wheel-artifact
            path: dist/*.whl
    
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
            - uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with: 
                workload_identity_provider: 
                  projects/${{secrets.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.WIF_POOL_NAME}}/providers/${{secrets.WIF_PROVIDER_NAME}}
                service_account: 
                  "${{secrets.WIF_SA_NAME}}@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com"
                create_credentials_file: true
                access_token_lifetime: 60
            - name: Download built artifacts
              uses: actions/download-artifact@v4
              with: 
                name: wheel-artifact
                path: dist
            - name: Set up Python
              uses: actions/setup-python@v4
            - name: Install Twine & Keyrings
              run: pip install twine keyring keyrings.google-artifactregistry-auth
            - name: Upload the artifact to google registry
              env:
                ARTIFACT_REGISTRY_PYPI_URL: ${{secrets.ARTIFACT_REGISTRY_PYPI_URL}}
              run: |
                twine upload --repository-url " $ARTIFACT_REGISTRY_PYPI_URL" \
                --verbose dist/*.whl
    
    dockerize:
        runs-on: ubuntu-latest
        needs: deploy
        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
          - uses: actions/checkout@v4
        
          - name: Authentificate to GCP
            id: auth
            uses: google-github-actions/auth@v2
            with:
              token_format: access_token
              workload_identity_provider: 
                projects/${{secrets.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.WIF_POOL_NAME}}/providers/${{secrets.WIF_PROVIDER_NAME}}
              service_account: 
                "${{secrets.WIF_SA_NAME}}@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com"
              create_credentials_file: true
              access_token_lifetime: 1000
            
          - name: credentials
            run: cat ${{env.GOOGLE_APPLICATION_CREDENTIALS}}  

          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
                username: oauth2accesstoken
                password: ${{ steps.auth.outputs.access_token }}
          
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2 
               
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
      
          - name: Build Docker
            uses: docker/build-push-action@v6
            with:
                push: true
                context: ./docker/
                build-args: |
                    LOCATION=${{ secrets.GCP_REGION }}
                    PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
                    REPO=${{ secrets.PYTHON_REPOSETORY_NAME }}
                    PACKAGE_NAME=${{ secrets.PYTHON_PACKAGE_NAME }}
                secret-files:
                    key_repo=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
                tags: |
                    ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_REPO_NAME }}/rec-sys-app:v1.0