name: python-packaging
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lock_checking:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uv lock --locked

    linting:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install ruff
        - run: ruff check

    formatting:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install ruff
        - run: ruff format
    
    types:
        runs-on: ubuntu-latest
        needs: [lock_checking]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - run: pip install mypy
        - run: mypy .

    tests:
        runs-on: ubuntu-latest
        needs: [linting, formatting, types]
        strategy:
            matrix:
                python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4  
          with:
            python-version: ${{matrix.python-version}}
        - uses: ./.github/actions/setup
        - run: uv sync
        # - run: uv run pytest
    
    build:
        runs-on: ubuntu-latest
        needs: [tests]
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        - uses: ./.github/actions/setup
        - name: "Setup the UV dependencies"  
          run: uv sync
        - name: Build the artifact
          run: uv build --wheel
        - name: Upload built artifacts
          uses: actions/upload-artifact@v4
          with:
            name: wheel-artifact
            path: dist/*.whl
    
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
            - uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v0.4.0
              with: 
                workload_identity_provider: 
                  projects/${{secrets.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.WIF_POOL_NAME}}/providers/${{secrets.WIF_PROVIDER_NAME}}
                service_account: 
                  ${{secrets.WIF_SA_NAME}}@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com
            - name: Download built artifacts
              uses: actions/download-artifact@v4
              with: 
                name: wheel-artifact
                path: dist
            - name: Set up Python
              uses: actions/setup-python@v4
            - name: Install Twine
              run: pip install twine
            - name: Upload the artifact to google registry
              env:
                ARTIFACT_REGISTRY_PYPI_URL: ${{secrets.ARTIFACT_REGISTRY_PYPI_URL}}
              run: |
                twine upload --repository-url "$ARTIFACT_REGISTRY_PYPI_URL" \
                dist/*.whl
    
    



    
    

    

    